algorithm: SAST
save_dir: ./saved_models
save_name: fgvc
resume: False
load_path: ./saved_models/fgvc/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
train_sampler: RandomSampler
dataset: fgvcaircraft
data_dir: /root/.cache/kagglehub/datasets/konszer/cpl-datasets/versions/1/FGVCAircraft
num_classes: 100 
num_labels: 200
img_size: 224
net: clip_maple_vit_b_32
net_from_name: False
amp: False
epoch: 50
num_train_iter: 11950
num_eval_iter: 239
warm_up_iter: 239
batch_size: 4
num_workers: 4

optim: SGD
lr: 0.02
momentum: 0.9
weight_decay: 0.05
layer_decay: 1.0
uratio: 7
hard_label: True
eval_batch_size: 128
model_dir: ./training_dynamics/fgvc/
base_thresh: 0.6
sigma: 1.0
fusion_T: 1.0
v11_attr_path: Semi-supervised-learning/semilearn/datasets/cv_datasets/attr/fgvc.json