algorithm: SAST_tl
save_dir: ./saved_models
save_name: flowers_tl
resume: False
load_path: ./saved_models/flowers_tl/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
train_sampler: RandomSampler
dataset: flowers102
data_dir: /root/.cache/kagglehub/datasets/konszer/cpl-datasets/versions/1/Flowers102
num_classes: 102
num_labels: 204
img_size: 224
net: clip_maple_vit_b_32
net_from_name: False
epoch: 50
num_train_iter: 2450
num_eval_iter: 49
warm_up_iter: 49
batch_size: 16
num_workers: 0
uratio: 1
optim: SGD
lr: 0.02
momentum: 0.9
weight_decay: 0.05
layer_decay: 1.0
hard_label: True
eval_batch_size: 128
model_dir: ./training_dynamics/flowers_tl/
base_thresh: 0.95
sigma: 1.0
consistency_penalty: 0.1
fusion_T: 1
v11_attr_path: Semi-supervised-learning/semilearn/datasets/cv_datasets/attr/flowers.json