algorithm: SAST
save_dir: ./saved_models
save_name: resisc
resume: False
load_path: ./saved_models/resisc/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
train_sampler: RandomSampler
dataset: resisc45
data_dir: /root/.cache/kagglehub/datasets/konszer/cpl-datasets/versions/1/RESISC45
num_classes: 45
num_labels: 90
img_size: 224
net: clip_maple_vit_b_32
net_from_name: False
amp: False
epoch: 50
num_train_iter: 11250
num_eval_iter: 225
warm_up_iter: 225
batch_size: 4
num_workers: 4

optim: SGD
lr: 0.02
momentum: 0.9
weight_decay: 0.05
layer_decay: 1.0
uratio: 7
hard_label: True
eval_batch_size: 128
model_dir: ./training_dynamics/resisc/
base_thresh: 0.85
prototype_ulb_ratio_start: 6
prototype_ulb_ratio_end: 8
sigma: 1.0
enable_analysis_logging: True
v11_attr_path: Semi-supervised-learning/semilearn/datasets/cv_datasets/attr/resisc.json
anchor_num_end: 0.8